-- Create the schedules table
create table if not exists public.schedules (
  id bigint generated by default as identity not null,
  text text not null,
  enviar_em timestamp with time zone not null,
  instance text not null,
  api_key text null,
  group_filter text null,
  min_size_group numeric null,
  mention_everyone boolean null default false,
  status text not null default 'pending'::text,
  enviado_em timestamp with time zone null,
  midia bytea null,
  error_message text null,
  type text not null default 'text',
  payload jsonb null,
  constraint schedules_pkey primary key (id)
);

alter table public.schedules
add column if not exists type text not null default 'text',
add column if not exists payload jsonb null;

-- Create Storage Bucket for Schedules
insert into storage.buckets (id, name, public)
values ('schedules', 'schedules', true)
on conflict (id) do nothing;

-- Policy to allow public access to schedules bucket
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'schedules' );

-- Policy to allow authenticated uploads to schedules bucket
create policy "Authenticated Upload"
  on storage.objects for insert
  with check ( bucket_id = 'schedules' AND auth.role() = 'authenticated' );

-- Create an index on status and enviar_em for faster worker polling
create index if not exists idx_schedules_status_enviar_em on public.schedules (status, enviar_em);

-- Enable Row Level Security (RLS)
alter table public.schedules enable row level security;

-- Create a policy to allow all access (since this is an internal dashboard)
-- You can restrict this later if needed
create policy "Allow all access"
on public.schedules
for all
using (true)
with check (true);
