-- Create the schedules table
create table if not exists public.schedules (
  id bigint generated by default as identity not null,
  text text not null,
  enviar_em timestamp with time zone not null,
  instance text not null,
  api_key text null,
  group_filter text null,
  min_size_group numeric null,
  mention_everyone boolean null default false,
  status text not null default 'pending'::text,
  enviado_em timestamp with time zone null,
  midia bytea null,
  error_message text null,
  type text not null default 'text',
  payload jsonb null,
  constraint schedules_pkey primary key (id)
);

alter table public.schedules
add column if not exists type text not null default 'text',
add column if not exists payload jsonb null;

-- Create Storage Bucket for Schedules
insert into storage.buckets (id, name, public)
values ('schedules', 'schedules', true)
on conflict (id) do nothing;

-- Policy to allow public access to schedules bucket
-- Policy to allow public access to schedules bucket
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'schedules' );

-- Policy to allow authenticated and anon uploads to schedules bucket
-- Policy to allow authenticated and anon uploads to schedules bucket
drop policy if exists "Authenticated Upload" on storage.objects;
create policy "Authenticated Upload"
  on storage.objects for insert
  with check ( bucket_id = 'schedules' AND (auth.role() = 'authenticated' OR auth.role() = 'anon') );

-- Create an index on status and enviar_em for faster worker polling
create index if not exists idx_schedules_status_enviar_em on public.schedules (status, enviar_em);

-- Enable Row Level Security (RLS)
alter table public.schedules enable row level security;

-- Create a policy to allow all access (since this is an internal dashboard)
-- You can restrict this later if needed
create policy "Allow all access"
on public.schedules
for all
using (true)
with check (true);

-- Settings Table
create table if not exists settings (
  id uuid default gen_random_uuid() primary key,
  key text unique not null,
  value jsonb not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed defaults
insert into settings (key, value, description) values
('cleanup_retention_days', '30', 'Days to keep sent media'),
('worker_rate_limit_ms', '2000', 'Delay between messages in milliseconds'),
('worker_poll_interval_ms', '5000', 'Worker polling frequency')
on conflict (key) do nothing;

alter table settings enable row level security;

create policy "Enable read access for all users"
on settings for select
using (true);

create policy "Enable write access for authenticated users"
on settings for insert
with check (auth.role() = 'authenticated');

create policy "Enable update access for authenticated users"
on settings for update
using (auth.role() = 'authenticated');
